version: '3'

services:
  # server
  node-app:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: NodeApp
    restart: always
    ports: 
      - 30000:30000
    depends_on: 
      - mongo
    environment: 
      MONGO_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin"

  # database
  mongo:
    image: mongo
    container_name: MongoDB
    volumes: 
      - mongo-volume:/data/db
    ports:
      # - '27017-27019:27017-27019'
      - '${MONGO_PORT}:${MONGO_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE}"
  # db admin panel
  mongo-express:
    image: mongo-express
    container_name: MongoExpressAdmin
    # restart: always
    ports:
      - 8888:8081
    depends_on: 
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      MONGOEXPRESS_LOGIN: dev
      MONGOEXPRESS_PASSWORD: dev
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}

  # mqtt broker
  # broker:
  #   build: 
  #     context: ./broker
  #     dockerfile: Dockerfile
  #   container_name: MqttBroker
  #   restart: always
  #   ports: 
  #     - 8883:8883
  #     - 9001:9001
  #   depends_on: 
  #     - mongo
  #   environment: 
  #     MONGO_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin"



volumes:
  mongo-volume: